-- ProjetoGaragem — seed inicial (cars + parts)
-- Execute após `supabase/schema.sql`.

begin;

-- =========================
-- CARS (15+)
-- =========================

insert into public.cars (
  slug,
  name,
  brand,
  model,
  year_start,
  year_end,
  engine_options,
  power_cv,
  torque_nm,
  weight_kg,
  category,
  fuel_type,
  transmission_options,
  common_issues,
  avg_price_min,
  avg_price_max
)
values
  (
    'civic-g8',
    'Honda Civic G8 (2006–2011)',
    'Honda',
    'Civic G8',
    2006,
    2011,
    '["1.8 i-VTEC (R18A)","2.0 i-VTEC (K20) — versões específicas"]'::jsonb,
    140,
    174,
    1250,
    'sedan',
    'flex/gasolina',
    '["manual","automático"]'::jsonb,
    array['coxins de motor','bandejas/buchas de suspensão','arrefecimento (manutenção preventiva)'],
    35000,
    65000
  ),
  (
    'civic-g9',
    'Honda Civic G9 (2012–2016)',
    'Honda',
    'Civic G9',
    2012,
    2016,
    '["1.8 i-VTEC (R18Z)","2.0 i-VTEC (K20) — versões específicas"]'::jsonb,
    143,
    174,
    1270,
    'sedan',
    'flex/gasolina',
    '["manual","automático"]'::jsonb,
    array['bandejas/buchas de suspensão','ruídos internos','manutenção preventiva de arrefecimento'],
    60000,
    98000
  ),
  (
    'gol-g5',
    'VW Gol G5 (2008–2013)',
    'Volkswagen',
    'Gol G5',
    2008,
    2013,
    '["1.0 Flex","1.6 Flex"]'::jsonb,
    104,
    153,
    1040,
    'hatch',
    'flex',
    '["manual","automático"]'::jsonb,
    array['buchas/coxins de suspensão','vibrações e ruídos','arrefecimento em uso severo'],
    20000,
    42000
  ),
  (
    'golf-mk7',
    'VW Golf MK7 (2013–2020)',
    'Volkswagen',
    'Golf MK7',
    2013,
    2020,
    '["1.4 TSI","1.6 MSI","2.0 TSI (GTI) — ver modelo GTI específico"]'::jsonb,
    150,
    250,
    1250,
    'hatch',
    'gasolina/flex',
    '["manual","automático"]'::jsonb,
    array['manutenção de câmbio (quando aplicável)','sensores/eletrônica','custo de peças maior'],
    75000,
    150000
  ),
  (
    'golf-gti-mk7',
    'VW Golf GTI MK7',
    'Volkswagen',
    'Golf GTI MK7',
    2013,
    2020,
    '["2.0 TSI (EA888)"]'::jsonb,
    220,
    350,
    1350,
    'esportivo',
    'gasolina',
    '["manual","automático (DSG)"]'::jsonb,
    array['custo alto de manutenção preventiva','câmbio DSG (manter revisões)','qualidade de combustível'],
    120000,
    220000
  ),
  (
    'hb20-2012-2019',
    'Hyundai HB20 1.0/1.6 (2012–2019)',
    'Hyundai',
    'HB20',
    2012,
    2019,
    '["1.0 Flex","1.6 Flex"]'::jsonb,
    128,
    161,
    1020,
    'hatch',
    'flex',
    '["manual","automático"]'::jsonb,
    array['suspensão dianteira (batentes/buchas)','direção (manutenção preventiva)','acabamentos internos'],
    35000,
    85000
  ),
  (
    'onix-2012-2019',
    'Chevrolet Onix 1.0/1.4 (2012–2019)',
    'Chevrolet',
    'Onix',
    2012,
    2019,
    '["1.0 Flex","1.4 Flex"]'::jsonb,
    106,
    134,
    1050,
    'hatch',
    'flex',
    '["manual","automático"]'::jsonb,
    array['arrefecimento (manutenção em dia)','buchas de suspensão','ruídos internos'],
    35000,
    82000
  ),
  (
    'corolla-xei-2008-2014',
    'Toyota Corolla XEI (2008–2014)',
    'Toyota',
    'Corolla XEI',
    2008,
    2014,
    '["1.8 Flex","2.0 Flex (XEI)"]'::jsonb,
    153,
    196,
    1310,
    'sedan',
    'flex',
    '["manual","automático"]'::jsonb,
    array['suspensão (buchas/bandejas)','freios em uso urbano','manutenção preventiva geral'],
    52000,
    98000
  ),
  (
    'palio-weekend',
    'Fiat Palio Weekend',
    'Fiat',
    'Palio Weekend',
    2003,
    2020,
    '["1.4 Fire Flex","1.6 Flex","1.8 E.torQ (Adventure)"]'::jsonb,
    115,
    174,
    1140,
    'wagon',
    'flex',
    '["manual"]'::jsonb,
    array['trincas/folgas em suspensão','arrefecimento','acabamento e ruídos'],
    22000,
    52000
  ),
  (
    'fiesta-st',
    'Ford Fiesta ST',
    'Ford',
    'Fiesta ST',
    2013,
    2017,
    '["1.6 EcoBoost Turbo"]'::jsonb,
    182,
    240,
    1160,
    'esportivo',
    'gasolina',
    '["manual"]'::jsonb,
    array['custo de peças importadas','arrefecimento e lubrificação (uso severo)','pneus/freios (desgaste)'],
    70000,
    140000
  ),
  (
    'clio-rs',
    'Renault Clio RS',
    'Renault',
    'Clio RS',
    2006,
    2016,
    '["2.0 16V aspirado","1.6 Turbo (varia por geração)"]'::jsonb,
    200,
    240,
    1200,
    'esportivo',
    'gasolina',
    '["manual","automático"]'::jsonb,
    array['peças importadas (disponibilidade)','suspensão firme (desgaste)','manutenção especializada'],
    80000,
    180000
  ),
  (
    'lancer',
    'Mitsubishi Lancer',
    'Mitsubishi',
    'Lancer',
    2007,
    2017,
    '["2.0 16V","2.0 GT (variações)"]'::jsonb,
    160,
    197,
    1340,
    'sedan',
    'gasolina/flex',
    '["manual","automático (CVT)"]'::jsonb,
    array['câmbio CVT (manutenção correta)','custo de peças','consumo em uso urbano'],
    50000,
    110000
  ),
  (
    'impreza-wrx',
    'Subaru Impreza WRX',
    'Subaru',
    'Impreza WRX',
    2006,
    2014,
    '["2.0 Turbo AWD","2.5 Turbo AWD (varia)"]'::jsonb,
    265,
    343,
    1450,
    'esportivo',
    'gasolina',
    '["manual"]'::jsonb,
    array['manutenção especializada (turbo/AWD)','custo e disponibilidade de peças','consumo'],
    140000,
    260000
  ),
  (
    'fit-2003-2008',
    'Honda Fit (2003–2008)',
    'Honda',
    'Fit',
    2003,
    2008,
    '["1.4 i-DSI","1.5 i-VTEC"]'::jsonb,
    105,
    143,
    1060,
    'hatch',
    'gasolina/flex',
    '["manual","automático (CVT/AT)"]'::jsonb,
    array['suspensão (buchas/bandejas)','arrefecimento (preventivo)','manutenção de câmbio (quando aplicável)'],
    28000,
    60000
  ),
  (
    'peugeot-206',
    'Peugeot 206',
    'Peugeot',
    '206',
    1999,
    2010,
    '["1.0/1.4","1.6 16V"]'::jsonb,
    109,
    147,
    1020,
    'hatch',
    'gasolina/flex',
    '["manual","automático"]'::jsonb,
    array['arrefecimento (atenção a vazamentos)','suspensão dianteira','elétrica/eletrônica (idade)'],
    12000,
    32000
  )
on conflict (slug) do nothing;

-- =========================
-- PARTS (80+)
-- =========================

insert into public.parts (
  slug,
  name,
  category,
  subcategory,
  brand,
  description,
  price_min,
  price_max,
  compatible_cars,
  affiliate_url,
  affiliate_store,
  image_url,
  notes
)
values
  -- Suspensão
  (
    'tein-coilover-street-advance-z',
    'Coilover Street Advance Z',
    'Suspensão',
    'Coilover',
    'Tein',
    'Coilover para uso de rua, com ajuste de altura e foco em dirigibilidade.',
    6500,
    14000,
    array['civic-g8','civic-g9','fit-2003-2008'],
    null,
    null,
    null,
    'Aplicação depende do ano/versão. Verificar kit correto.'
  ),
  (
    'kw-coilover-v1',
    'Coilover Variant 1 (V1)',
    'Suspensão',
    'Coilover',
    'KW',
    'Kit premium para altura ajustável com acerto focado em rua.',
    12000,
    28000,
    array['golf-mk7','golf-gti-mk7'],
    null,
    null,
    null,
    null
  ),
  (
    'bc-racing-coilover-br-series',
    'Coilover BR Series',
    'Suspensão',
    'Coilover',
    'BC Racing',
    'Coilover com bom custo-benefício, acerto mais firme e ajustes amplos.',
    9000,
    20000,
    array['civic-g8','civic-g9','golf-mk7','lancer'],
    null,
    null,
    null,
    null
  ),
  (
    'raceland-coilover-ultimo',
    'Coilover Ultimo',
    'Suspensão',
    'Coilover',
    'Raceland',
    'Opção de entrada para baixar o carro com ajuste de altura.',
    3500,
    8500,
    array['gol-g5','peugeot-206'],
    null,
    null,
    null,
    'Conforto e durabilidade variam. Ideal revisar instalação.'
  ),
  (
    'eibach-molas-pro-kit',
    'Mola esportiva Pro-Kit',
    'Suspensão',
    'Molas',
    'Eibach',
    'Molas esportivas para baixar com equilíbrio (rua).',
    1600,
    3200,
    array['civic-g8','civic-g9','golf-mk7','corolla-xei-2008-2014','fit-2003-2008'],
    null,
    null,
    null,
    null
  ),
  (
    'hr-molas-sport',
    'Mola esportiva Sport',
    'Suspensão',
    'Molas',
    'H&R',
    'Molas esportivas com drop moderado e acerto firme.',
    1800,
    3600,
    array['golf-mk7','golf-gti-mk7'],
    null,
    null,
    null,
    null
  ),
  (
    'koni-amortecedor-sport',
    'Amortecedor esportivo Sport (ajustável)',
    'Suspensão',
    'Amortecedor',
    'Koni',
    'Amortecedor esportivo ajustável para uso de rua/pista leve.',
    3800,
    9500,
    array['civic-g8','civic-g9','golf-mk7','lancer'],
    null,
    null,
    null,
    null
  ),
  (
    'bilstein-b6-performance',
    'Amortecedor B6 Performance',
    'Suspensão',
    'Amortecedor',
    'Bilstein',
    'Amortecedor esportivo focado em controle e durabilidade.',
    4200,
    11000,
    array['golf-mk7','golf-gti-mk7'],
    null,
    null,
    null,
    null
  ),
  (
    'whiteline-buchas-poli',
    'Buchas em poliuretano (kit)',
    'Suspensão',
    'Buchas',
    'Whiteline',
    'Kit de buchas de poliuretano para reduzir folgas e melhorar resposta.',
    800,
    2600,
    array['civic-g8','civic-g9','golf-mk7','lancer'],
    null,
    null,
    null,
    'Pode aumentar NVH (vibração/ruído).'
  ),
  (
    'superpro-buchas-poli',
    'Buchas em poliuretano (kit)',
    'Suspensão',
    'Buchas',
    'SuperPro',
    'Buchas de poliuretano para uso rua/pista leve.',
    900,
    2900,
    array['golf-mk7','golf-gti-mk7','lancer'],
    null,
    null,
    null,
    null
  ),
  (
    'barra-estabilizadora-reforcada',
    'Barra estabilizadora reforçada',
    'Suspensão',
    'Estabilizadora',
    null,
    'Barra mais rígida para reduzir rolagem em curvas.',
    700,
    2200,
    '{}'::text[],
    null,
    null,
    null,
    'Peça depende do modelo. Se não houver aplicação, exige adaptação.'
  ),
  (
    'coxim-motor-reforcado',
    'Coxim de motor reforçado',
    'Suspensão',
    'Coxim',
    null,
    'Coxim mais rígido para reduzir tranco e movimentação do conjunto.',
    300,
    1200,
    '{}'::text[],
    null,
    null,
    null,
    'Pode aumentar vibração em marcha lenta.'
  ),

  -- Rodas e pneus
  (
    'oz-racing-roda-17',
    'Roda 17" liga leve',
    'Rodas e Pneus',
    'Roda',
    'OZ Racing',
    'Roda 17" para setup rua com visual esportivo.',
    4500,
    12000,
    '{}'::text[],
    null,
    null,
    null,
    'Compatibilidade depende de furação/offset e freios.'
  ),
  (
    'enkei-roda-17',
    'Roda 17" liga leve',
    'Rodas e Pneus',
    'Roda',
    'Enkei',
    'Roda 17" leve e resistente para uso urbano e track day leve.',
    5200,
    13000,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'sparco-roda-17',
    'Roda 17" liga leve',
    'Rodas e Pneus',
    'Roda',
    'Sparco',
    'Roda 17" com visual motorsport.',
    4200,
    11000,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'bbs-roda-18',
    'Roda 18" liga leve',
    'Rodas e Pneus',
    'Roda',
    'BBS',
    'Roda 18" premium, foco em estética e performance.',
    9000,
    22000,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'work-roda-18',
    'Roda 18" liga leve',
    'Rodas e Pneus',
    'Roda',
    'Work',
    'Roda 18" estilo JDM, opções de tala e offset.',
    9500,
    26000,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'rays-roda-18',
    'Roda 18" liga leve',
    'Rodas e Pneus',
    'Roda',
    'Rays',
    'Roda 18" forjada/alta qualidade (depende da linha).',
    11000,
    32000,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'roda-15-economica-esportiva',
    'Roda 15" econômica esportiva',
    'Rodas e Pneus',
    'Roda',
    null,
    'Roda 15" para daily com visual esportivo e custo menor.',
    1800,
    5200,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'michelin-pneu-205-40r17',
    'Pneu 205/40R17 perfil baixo',
    'Rodas e Pneus',
    'Pneu',
    'Michelin',
    'Pneu de perfil baixo para resposta e visual; exige atenção em buracos.',
    700,
    1400,
    '{}'::text[],
    null,
    null,
    null,
    'Perfil baixo aumenta risco de amassar roda.'
  ),
  (
    'pirelli-pneu-225-45r18',
    'Pneu 225/45R18',
    'Rodas e Pneus',
    'Pneu',
    'Pirelli',
    'Medida comum em 18", equilíbrio entre conforto e grip.',
    780,
    1600,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'bridgestone-pneu-195-55r15',
    'Pneu 195/55R15',
    'Rodas e Pneus',
    'Pneu',
    'Bridgestone',
    'Medida para uso diário com bom conforto.',
    420,
    980,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'espacador-roda-15mm',
    'Espaçador de roda 15mm',
    'Rodas e Pneus',
    'Espaçador',
    null,
    'Espaçador 15mm para ajuste de fitment.',
    180,
    520,
    '{}'::text[],
    null,
    null,
    null,
    'Exige prisioneiros/parafusos adequados.'
  ),
  (
    'espacador-roda-20mm',
    'Espaçador de roda 20mm',
    'Rodas e Pneus',
    'Espaçador',
    null,
    'Espaçador 20mm para ajuste agressivo de fitment.',
    220,
    650,
    '{}'::text[],
    null,
    null,
    null,
    'Pode exigir alargador de para-lama e alinhamento.'
  ),

  -- Motor e Performance
  (
    'kn-intake-cold-air',
    'Intake cold air',
    'Motor e Performance',
    'Intake',
    'K&N',
    'Sistema de admissão com maior fluxo e som mais presente.',
    1200,
    4200,
    array['civic-g8','civic-g9','golf-mk7','gol-g5','hb20-2012-2019','onix-2012-2019'],
    null,
    null,
    null,
    'Pode exigir ajuste (tune) para melhor resultado.'
  ),
  (
    'aem-intake-cold-air',
    'Intake cold air',
    'Motor e Performance',
    'Intake',
    'AEM',
    'Admissão com foco em resposta e fluxo.',
    1600,
    5200,
    array['golf-mk7','golf-gti-mk7'],
    null,
    null,
    null,
    null
  ),
  (
    'injen-intake',
    'Intake cold air',
    'Motor e Performance',
    'Intake',
    'Injen',
    'Admissão esportiva para melhora de resposta e som.',
    1500,
    5200,
    array['civic-g8','civic-g9','fit-2003-2008'],
    null,
    null,
    null,
    null
  ),
  (
    'kn-filtro-esportivo',
    'Filtro de ar esportivo',
    'Motor e Performance',
    'Filtro',
    'K&N',
    'Filtro de reposição esportivo lavável.',
    280,
    650,
    '{}'::text[],
    null,
    null,
    null,
    'Compatível quando a medida do filtro bate com a caixa original.'
  ),
  (
    'bmc-filtro-esportivo',
    'Filtro de ar esportivo',
    'Motor e Performance',
    'Filtro',
    'BMC',
    'Filtro esportivo para maior fluxo de ar.',
    300,
    750,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'borla-escape-catback-inox',
    'Escape catback inox',
    'Motor e Performance',
    'Escape',
    'Borla',
    'Catback em inox com som mais encorpado e melhor fluxo.',
    5200,
    14000,
    array['golf-gti-mk7'],
    null,
    null,
    null,
    null
  ),
  (
    'magnaflow-escape-catback-inox',
    'Escape catback inox',
    'Motor e Performance',
    'Escape',
    'Magnaflow',
    'Catback em inox para melhorar fluxo e timbre.',
    4800,
    13000,
    array['golf-mk7','golf-gti-mk7'],
    null,
    null,
    null,
    null
  ),
  (
    'magflowbr-escape-catback-inox',
    'Escape catback inox',
    'Motor e Performance',
    'Escape',
    'MagFlow BR',
    'Catback inox (mercado BR) com foco em custo-benefício.',
    2200,
    7500,
    array['gol-g5','hb20-2012-2019','onix-2012-2019','civic-g8'],
    null,
    null,
    null,
    null
  ),
  (
    'downpipe-3-pol',
    'Downpipe 3" (tubo)',
    'Motor e Performance',
    'Downpipe',
    null,
    'Downpipe 3" para reduzir restrição (aplicação turbo).',
    900,
    3500,
    array['golf-gti-mk7'],
    null,
    null,
    null,
    'Pode exigir remap e atenção à legislação/inspeção.'
  ),
  (
    'intercooler-front-mount',
    'Intercooler front mount',
    'Motor e Performance',
    'Intercooler',
    null,
    'Intercooler frontal para setups turbo e controle de IAT.',
    1500,
    6500,
    array['golf-gti-mk7','impreza-wrx'],
    null,
    null,
    null,
    null
  ),
  (
    'turbina-t3-t4',
    'Turbina T3/T4',
    'Motor e Performance',
    'Turbo',
    null,
    'Turbina T3/T4 (tamanho genérico) para projetos turbo.',
    1800,
    6500,
    '{}'::text[],
    null,
    null,
    null,
    'Projeto turbo exige dimensionamento e acerto (tune).'
  ),
  (
    'wastegate-externa-38mm',
    'Wastegate externa 38mm',
    'Motor e Performance',
    'Wastegate',
    null,
    'Controle de pressão de turbo com wastegate externa 38mm.',
    450,
    1800,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'tial-bov',
    'BOV (válvula blow-off)',
    'Motor e Performance',
    'BOV',
    'Tial',
    'Válvula blow-off para alívio de pressão em setups turbo.',
    900,
    3200,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'hks-bov',
    'BOV (válvula blow-off)',
    'Motor e Performance',
    'BOV',
    'HKS',
    'BOV clássica do mercado JDM para setups turbo.',
    1100,
    4500,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'turbosmart-bov',
    'BOV (válvula blow-off)',
    'Motor e Performance',
    'BOV',
    'Turbosmart',
    'BOV para setups turbo com boa vedação e durabilidade.',
    900,
    3800,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'ngk-vela-iridium',
    'Vela de ignição iridium',
    'Motor e Performance',
    'Ignição',
    'NGK',
    'Velas iridium para melhor ignição e estabilidade.',
    220,
    680,
    '{}'::text[],
    null,
    null,
    null,
    'Aplicação depende do motor/rosca/grau térmico.'
  ),
  (
    'denso-vela-iridium',
    'Vela de ignição iridium',
    'Motor e Performance',
    'Ignição',
    'Denso',
    'Velas iridium para resposta e durabilidade.',
    240,
    750,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'cabo-vela-esportivo',
    'Cabo de vela esportivo',
    'Motor e Performance',
    'Ignição',
    null,
    'Cabos de vela com melhor isolamento e acabamento.',
    180,
    650,
    array['peugeot-206','gol-g5'],
    null,
    null,
    null,
    'Nem todo motor usa cabos (muitos usam bobina individual).'
  ),
  (
    'bobina-ignicao-reforcada',
    'Bobina de ignição reforçada',
    'Motor e Performance',
    'Ignição',
    null,
    'Bobinas reforçadas para setups com maior demanda (tune/boost).',
    450,
    2200,
    '{}'::text[],
    null,
    null,
    null,
    'Verificar referência exata para o motor.'
  ),
  (
    'injetor-440cc',
    'Injetor de combustível 440cc',
    'Motor e Performance',
    'Combustível',
    null,
    'Injetores maiores para projetos turbo/remap.',
    600,
    1800,
    '{}'::text[],
    null,
    null,
    null,
    'Requer remap e, às vezes, upgrade de bomba/regulador.'
  ),
  (
    'injetor-550cc',
    'Injetor de combustível 550cc',
    'Motor e Performance',
    'Combustível',
    null,
    'Injetores para setups com mais potência (turbo).',
    700,
    2200,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'remap-ecu',
    'Mapa de injeção (remap ECU)',
    'Motor e Performance',
    'Remap',
    null,
    'Remap para melhorar resposta, potência e corrigir upgrades.',
    800,
    3500,
    '{}'::text[],
    null,
    null,
    null,
    'Sempre fazer com profissional e combustível adequado.'
  ),
  (
    'chip-performance',
    'Chip de performance (piggyback)',
    'Motor e Performance',
    'Remap',
    null,
    'Piggyback simples para ajustes leves.',
    400,
    1800,
    '{}'::text[],
    null,
    null,
    null,
    'Resultados variam. Remap dedicado costuma ser melhor.'
  ),
  (
    'cabecote-polido',
    'Cabeçote polido (serviço)',
    'Motor e Performance',
    'Preparação',
    null,
    'Serviço de fluxo (port/polish) no cabeçote.',
    1200,
    4500,
    '{}'::text[],
    null,
    null,
    null,
    'Exige mão de obra especializada.'
  ),
  (
    'comando-valvulas-esportivo',
    'Comando de válvulas esportivo',
    'Motor e Performance',
    'Preparação',
    null,
    'Comando para alterar tempo de válvulas e faixa de potência.',
    900,
    4200,
    array['civic-g8','civic-g9','fit-2003-2008'],
    null,
    null,
    null,
    'Pode exigir molas de válvula e remap.'
  ),

  -- Freios
  (
    'disco-ventilado',
    'Disco de freio ventilado (par)',
    'Freios',
    'Disco',
    null,
    'Discos ventilados para maior resistência a fading.',
    400,
    1800,
    '{}'::text[],
    null,
    null,
    null,
    'Aplicação depende de diâmetro/furação.'
  ),
  (
    'ebc-pastilha-esportiva',
    'Pastilha de freio esportiva',
    'Freios',
    'Pastilha',
    'EBC',
    'Pastilhas com maior atrito e melhor resistência ao calor.',
    380,
    1200,
    array['civic-g8','civic-g9','golf-mk7','golf-gti-mk7','lancer'],
    null,
    null,
    null,
    null
  ),
  (
    'ferodo-pastilha-esportiva',
    'Pastilha de freio esportiva',
    'Freios',
    'Pastilha',
    'Ferodo',
    'Pastilhas para resposta e controle em uso mais forte.',
    320,
    1100,
    array['gol-g5','hb20-2012-2019','onix-2012-2019','corolla-xei-2008-2014'],
    null,
    null,
    null,
    null
  ),
  (
    'brembo-pastilha',
    'Pastilha de freio esportiva',
    'Freios',
    'Pastilha',
    'Brembo',
    'Pastilhas com foco em performance e consistência.',
    420,
    1500,
    array['golf-gti-mk7','impreza-wrx'],
    null,
    null,
    null,
    null
  ),
  (
    'fluido-freio-dot-4-5-1',
    'Fluido de freio DOT 4/5.1',
    'Freios',
    'Fluido',
    null,
    'Fluido com ponto de ebulição elevado (ideal para uso forte).',
    60,
    220,
    '{}'::text[],
    null,
    null,
    null,
    'Trocar periodicamente.'
  ),
  (
    'mangote-freio-malha-aco',
    'Mangote metálico (malha de aço)',
    'Freios',
    'Linha',
    null,
    'Linhas aeroquip para pedal mais firme.',
    280,
    1200,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'kit-big-brake-brembo',
    'Kit big brake',
    'Freios',
    'Big Brake',
    'Brembo',
    'Kit de pinças/discos maiores para alta performance.',
    12000,
    45000,
    array['golf-gti-mk7','impreza-wrx'],
    null,
    null,
    null,
    'Exige rodas compatíveis.'
  ),
  (
    'kit-big-brake-ap-racing',
    'Kit big brake',
    'Freios',
    'Big Brake',
    'AP Racing',
    'Kit de freio para uso forte/track day.',
    15000,
    52000,
    array['golf-gti-mk7','impreza-wrx'],
    null,
    null,
    null,
    null
  ),
  (
    'freio-mao-esportivo',
    'Freio de mão esportivo',
    'Freios',
    'Freio de mão',
    null,
    'Freio de mão hidráulico/estilo esportivo (uso específico).',
    300,
    1800,
    '{}'::text[],
    null,
    null,
    null,
    'Uso em via pública pode ser problema. Verificar legislação.'
  ),

  -- Estética e Bodykit
  (
    'lip-dianteiro-universal',
    'Lip dianteiro universal',
    'Estética e Bodykit',
    'Lip',
    null,
    'Lip universal para visual agressivo.',
    120,
    650,
    '{}'::text[],
    null,
    null,
    null,
    'Pode exigir adaptação e cuidado com altura.'
  ),
  (
    'lip-traseiro',
    'Lip traseiro',
    'Estética e Bodykit',
    'Lip',
    null,
    'Acabamento traseiro para visual mais baixo.',
    160,
    750,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'side-skirts',
    'Side skirts',
    'Estética e Bodykit',
    'Saias laterais',
    null,
    'Saias laterais para completar o conjunto.',
    220,
    1200,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'difusor-traseiro',
    'Difusor traseiro',
    'Estética e Bodykit',
    'Difusor',
    null,
    'Difusor para visual esportivo e acabamento.',
    250,
    1800,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'spoiler-teto',
    'Spoiler de teto',
    'Estética e Bodykit',
    'Aerofólio',
    null,
    'Spoiler de teto para hatch.',
    180,
    1100,
    array['gol-g5','golf-mk7','hb20-2012-2019','onix-2012-2019','fit-2003-2008','peugeot-206'],
    null,
    null,
    null,
    null
  ),
  (
    'capo-fibra-carbono',
    'Capô fibra de carbono',
    'Estética e Bodykit',
    'Capô',
    null,
    'Capô em carbono para redução de peso e visual.',
    3500,
    12000,
    array['civic-g8','civic-g9','golf-mk7','golf-gti-mk7','impreza-wrx'],
    null,
    null,
    null,
    'Pode exigir ajustes de encaixe e trava.'
  ),
  (
    'retrovisores-carbono',
    'Retrovisores carbono',
    'Estética e Bodykit',
    'Detalhes',
    null,
    'Capas/retrovisores com visual carbono.',
    200,
    1400,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'calha-chuva-fume',
    'Calha de chuva fumê',
    'Estética e Bodykit',
    'Acessório',
    null,
    'Calha fumê para visual e conforto.',
    120,
    450,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'pelicula-fume',
    'Película fumê (insulfilm)',
    'Estética e Bodykit',
    'Película',
    null,
    'Película para conforto térmico/privacidade.',
    180,
    1200,
    '{}'::text[],
    null,
    null,
    null,
    'Verificar limite permitido por lei.'
  ),
  (
    'farol-led-completo',
    'Farol de LED completo',
    'Estética e Bodykit',
    'Iluminação',
    null,
    'Conjunto de farol em LED (dependente de modelo).',
    900,
    6500,
    '{}'::text[],
    null,
    null,
    null,
    'Aplicação depende do carro. Se não existir kit, exige adaptação.'
  ),
  (
    'farol-neblina-led',
    'Farol de neblina LED',
    'Estética e Bodykit',
    'Iluminação',
    null,
    'Neblina em LED para melhor iluminação.',
    120,
    650,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'luz-freio-led',
    'Luz de freio LED',
    'Estética e Bodykit',
    'Iluminação',
    null,
    'Upgrade para LED nas lanternas/luz de freio.',
    60,
    300,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'soleira-iluminada',
    'Soleira iluminada',
    'Estética e Bodykit',
    'Detalhe interno/externo',
    null,
    'Soleiras com iluminação para visual premium.',
    150,
    900,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'kit-xenon-hid',
    'Kit xenon HID',
    'Estética e Bodykit',
    'Iluminação',
    null,
    'Kit xenon (HID) para farol (uso e legalidade variam).',
    180,
    900,
    '{}'::text[],
    null,
    null,
    null,
    'Verificar legislação e instalação correta (não ofuscar).'
  ),

  -- Interno
  (
    'sparco-volante-esportivo',
    'Volante esportivo',
    'Interno',
    'Volante',
    'Sparco',
    'Volante com pegada esportiva (rua/pista).',
    650,
    2200,
    '{}'::text[],
    null,
    null,
    null,
    'Exige cubo compatível e atenção ao airbag.'
  ),
  (
    'momo-volante-esportivo',
    'Volante esportivo',
    'Interno',
    'Volante',
    'Momo',
    'Volante clássico para setup street/track.',
    900,
    3200,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'nrg-volante-esportivo',
    'Volante esportivo',
    'Interno',
    'Volante',
    'NRG',
    'Volante esportivo para setup custom.',
    450,
    1800,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'cubo-volante',
    'Cubo de volante',
    'Interno',
    'Cubo',
    null,
    'Cubo específico para adaptar volante esportivo.',
    180,
    850,
    '{}'::text[],
    null,
    null,
    null,
    'Compatibilidade depende do carro/coluna.'
  ),
  (
    'sparco-banco-esportivo',
    'Banco esportivo',
    'Interno',
    'Banco',
    'Sparco',
    'Banco esportivo para suporte lateral.',
    1800,
    9500,
    '{}'::text[],
    null,
    null,
    null,
    'Pode exigir trilhos/adapter e regularização.'
  ),
  (
    'recaro-banco-esportivo',
    'Banco esportivo',
    'Interno',
    'Banco',
    'Recaro',
    'Banco premium com excelente ergonomia.',
    3500,
    18000,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'bride-banco-esportivo',
    'Banco esportivo',
    'Interno',
    'Banco',
    'Bride',
    'Banco JDM com foco em suporte lateral.',
    3800,
    22000,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'cinto-4-pontos-sparco',
    'Cinto 4 pontos',
    'Interno',
    'Cinto',
    'Sparco',
    'Cinto para uso em track day (com fixação adequada).',
    650,
    2600,
    '{}'::text[],
    null,
    null,
    null,
    'Uso exige pontos de ancoragem corretos.'
  ),
  (
    'cinto-4-pontos-omp',
    'Cinto 4 pontos',
    'Interno',
    'Cinto',
    'OMP',
    'Cinto para suporte em uso esportivo.',
    700,
    2800,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'cinto-4-pontos-sabelt',
    'Cinto 4 pontos',
    'Interno',
    'Cinto',
    'Sabelt',
    'Cinto premium para uso esportivo.',
    900,
    3800,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'gaiola-parcial',
    'Gaiola parcial',
    'Interno',
    'Segurança',
    null,
    'Gaiola parcial para rigidez e segurança (uso específico).',
    2200,
    9500,
    '{}'::text[],
    null,
    null,
    null,
    'Requer projeto/instalação e pode exigir documentação.'
  ),
  (
    'pedal-aluminio',
    'Pedal de alumínio (kit)',
    'Interno',
    'Pedaleira',
    null,
    'Pedais com melhor grip e visual.',
    120,
    650,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'alavanca-curta',
    'Alavanca de câmbio curta (short shifter)',
    'Interno',
    'Câmbio',
    null,
    'Reduz curso do câmbio para trocas mais rápidas.',
    180,
    1200,
    '{}'::text[],
    null,
    null,
    null,
    'Aplicação depende do câmbio/plataforma.'
  ),
  (
    'manopla-cambio-esportiva',
    'Manopla de câmbio esportiva',
    'Interno',
    'Câmbio',
    null,
    'Manopla com visual esportivo e melhor pegada.',
    80,
    450,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'defi-painel-digital',
    'Painel digital (cluster)',
    'Interno',
    'Instrumentação',
    'Defi',
    'Cluster digital para leitura e estética.',
    2500,
    12000,
    '{}'::text[],
    null,
    null,
    null,
    'Integração varia por carro.'
  ),
  (
    'aem-painel-digital',
    'Painel digital (display)',
    'Interno',
    'Instrumentação',
    'AEM',
    'Display/cluster para leitura de parâmetros.',
    1800,
    9500,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'medidor-boost',
    'Medidor de pressão do turbo (boost)',
    'Interno',
    'Instrumentação',
    null,
    'Medidor de boost para setups turbo.',
    180,
    1200,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'medidor-temp-oleo',
    'Medidor de temperatura do óleo',
    'Interno',
    'Instrumentação',
    null,
    'Leitura de temperatura do óleo para segurança.',
    180,
    1200,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'head-up-display',
    'Head-up display (HUD)',
    'Interno',
    'Eletrônicos',
    null,
    'HUD para projeção de velocidade/infos.',
    150,
    900,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),

  -- Som Automotivo
  (
    'jbl-subwoofer-12',
    'Subwoofer 12"',
    'Som Automotivo',
    'Subwoofer',
    'JBL',
    'Sub 12" para grave com boa eficiência.',
    320,
    1200,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'pioneer-subwoofer-12',
    'Subwoofer 12"',
    'Som Automotivo',
    'Subwoofer',
    'Pioneer',
    'Sub 12" para setup street.',
    280,
    1100,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'skar-subwoofer-12',
    'Subwoofer 12"',
    'Som Automotivo',
    'Subwoofer',
    'Skar',
    'Sub 12" com foco em SPL/custo-benefício.',
    450,
    1600,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'subwoofer-15',
    'Subwoofer 15"',
    'Som Automotivo',
    'Subwoofer',
    null,
    'Sub 15" para mais deslocamento e grave.',
    420,
    2200,
    '{}'::text[],
    null,
    null,
    null,
    'Requer caixa dimensionada.'
  ),
  (
    'caixa-selada-12',
    'Caixinha selada 12"',
    'Som Automotivo',
    'Caixa',
    null,
    'Caixa selada para sub 12" com grave mais controlado.',
    180,
    900,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'caixa-bandpass',
    'Caixinha bandpass',
    'Som Automotivo',
    'Caixa',
    null,
    'Caixa bandpass para mais eficiência em faixa específica.',
    220,
    1400,
    '{}'::text[],
    null,
    null,
    null,
    'Projeto influencia muito o resultado.'
  ),
  (
    'stetsom-mono-1000w',
    'Amplificador mono 1000W',
    'Som Automotivo',
    'Amplificador',
    'Stetsom',
    'Módulo mono para subwoofer (potência varia por modelo).',
    320,
    1600,
    '{}'::text[],
    null,
    null,
    null,
    'Dimensionar cabos/fusíveis.'
  ),
  (
    'taramps-mono-1000w',
    'Amplificador mono 1000W',
    'Som Automotivo',
    'Amplificador',
    'Taramps',
    'Módulo mono para subwoofer com boa eficiência.',
    300,
    1500,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'banda-mono-1000w',
    'Amplificador mono 1000W',
    'Som Automotivo',
    'Amplificador',
    'Banda',
    'Módulo mono para subwoofer (linha varia).',
    380,
    1800,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'amplificador-4-canais',
    'Amplificador 4 canais',
    'Som Automotivo',
    'Amplificador',
    null,
    'Amplificador para portas/tweeters (4 canais).',
    350,
    2200,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'alto-falante-6x9',
    'Alto-falante 6x9" coaxial',
    'Som Automotivo',
    'Alto-falante',
    null,
    '6x9" coaxial para traseira com bom rendimento.',
    160,
    850,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'alto-falante-6-5-2vias',
    'Alto-falante 6.5" 2 vias',
    'Som Automotivo',
    'Alto-falante',
    null,
    'Kit 2 vias para porta com melhor definição.',
    180,
    1200,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'tweeter-dome',
    'Tweeter dome',
    'Som Automotivo',
    'Tweeter',
    null,
    'Tweeter dome para brilho e detalhamento.',
    70,
    450,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'processador-dsp',
    'Processador de áudio DSP',
    'Som Automotivo',
    'DSP',
    null,
    'DSP para ajuste fino (EQ, crossovers, delay).',
    450,
    2800,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'cabo-rca-ouro',
    'Cabo RCA ouro (par)',
    'Som Automotivo',
    'Cabos',
    null,
    'RCA com melhor blindagem/conectores.',
    40,
    220,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'fio-potencia-0-awg',
    'Fio de potência 0 AWG',
    'Som Automotivo',
    'Cabos',
    null,
    'Cabo de alimentação para módulos potentes.',
    120,
    520,
    '{}'::text[],
    null,
    null,
    null,
    'Dimensionar de acordo com consumo e distância.'
  ),
  (
    'multimidia-2din-android',
    'Multimídia 2 din Android',
    'Som Automotivo',
    'Multimídia',
    null,
    'Central multimídia Android 2DIN.',
    450,
    2800,
    '{}'::text[],
    null,
    null,
    null,
    null
  ),
  (
    'camera-re',
    'Câmera de ré',
    'Som Automotivo',
    'Acessório',
    null,
    'Câmera de ré para manobras com segurança.',
    80,
    450,
    '{}'::text[],
    null,
    null,
    null,
    null
  )
on conflict (slug) do nothing;

commit;

